config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
end

	get 'add_applicant' => 'applicants#add_applicant'

	#get 'apply' => 'home#apply'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#home'
end

app/models/applicant.rb
class Applicant < ApplicationRecord
	  #For better indexing, would use has and belongs to many users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  #has_many :applicants
  validates_presence_of :name, uniqueness: true
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController

#for a live app, stronger parameters would be implemented using private methods
	def add_applicant

		@applicant = Applicant.create(name: params[:name], email: params[:email], applicant_id: params[:applicant_id],
			company_id: params[:company_id])
		@company = User.where(id: params[:company_id])
		if @applicant.save
			flash[:alert] = "Congratulations, You Have Succesfully Applied to #{@company.take.name}"
			redirect_to root_path
		else
			redirect_to root_path
		end

	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

#Added DEVISE Parameters, name, applicant & employer
    protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :applicant, :employer])
  end

end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  def home
  	@user = current_user
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/home.html.erb
<div id="home" style="text-align:center;overflow:auto;height:auto;">

 <%# NOTICES %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%# First PAGE %>


<h2>Welcome! Easy Hiring by Candidate Hector Moreno Bravo is in Session! </h2>
<% if !user_signed_in? %>
		<p>Please <%= link_to "Sign In", new_user_session_path %> or <%= link_to "Sign Up", new_user_registration_path %>  </p>
<% else %>
		<p><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %> </p>
<% end %>




  <%# FOR EMPLOYERS %>

	<% if user_signed_in? && current_user.employer? %>
		<h3> All Applicants </h3>
		<div class="panel panel-default">
		<% User.where(applicant: true).each do |a| %>
  			<div class="panel-heading">
  				<ul style="display:inline !important;">
			<% if Applicant.where({company_id: current_user.id, applicant_id: a.id}).exists? %>

  					<li ><p><b>Name:</b> <%= a.name %></p></li>
  					<%#<li><p><b>Email:</b> <%= link_to a.email, "#" ></p></li>%>
  				<p> --------------------------------------- </p>
  			</br>

  				</ul>
  			</br>
  			<% end %>

  		<% end %>

  <%# FOR APPLICANTS %>


	<% elsif user_signed_in? && current_user.applicant? %>

		<h3> All Companies Hiring </h3>
		<% User.where(employer: true).each do |e| %>
		  			</br>

			<% if !Applicant.where({company_id: e.id, applicant_id: current_user.id}).exists? %>
  			<ul style="display:inline !important;">
  				<li><b>Employer:</b> <%= e.name %>

  				<%= link_to "Apply", add_applicant_path(
  			:name => current_user.name, :email => current_user.email, applicant_id: current_user.id, 
  			:company_id => e.id), :style => "maring:40px; border:.5px white solid; background-color:#2db92d;text-decoration:none;color:white; padding:7px 7px;border-radius:9px;letter-spacing:1.5px;" %></li>
  			</ul>

		<% end %>
	<% end %>


<% end %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyApply</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" %>



    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= javascript_include_tag "//www.google.com/jsapi" %>
  </head>

  <body>
  	<%= link_to "Home Page", root_path, class: "btn btn-default", :style => 'margin:20px 0px 0px 20px;color:black;' if !current_page?(root_path)%>

  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>